controller_list:
  - name: fake_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - joint1
      - joint2
initial:  # Define initial robot poses per group
#  - group: arm
#    pose: home

  []