controller_list:
  - name: effort_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - j1
      - j2
      - j3
      - j4
      - j5
      - j6
  - name: velocity_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - j1
      - j2
      - j3
      - j4
      - j5
      - j6
  - name: position_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - j1
      - j2
      - j3
      - j4
      - j5
      - j6
  - name: joint_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - j1
      - j2
      - j3
      - j4
      - j5
      - j6